FROM python:3.12-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1

ENV PYTHONUNBUFFERED=1

RUN apt-get update && apt-get install -y \
    gcc \
    python3-dev \
    libffi-dev \
    libmagic1 \
    netcat-openbsd \
    curl \
    && rm -rf /var/lib/apt/lists/*


RUN pip install --no-cache-dir poetry==1.7.1

COPY pyproject.toml poetry.lock ./

RUN poetry config virtualenvs.create false \
    && poetry install --no-dev --no-interaction --no-ansi

COPY app/ ./app/

CMD [ "gunicorn", "app.main:app", "--bind", "0.0.0.0:8000" ]

