# Generated by Django 4.2.27 on 2026-03-02 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'admin'), ('patient', 'patient'), ('doctor', 'doctor')], default='patient', max_length=10),
        ),
    ]
