# Generated by Django 4.2.27 on 2026-03-30 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('admin', 'admin'), ('patient', 'patient'), ('doctor', 'doctor')], default='admin', max_length=10),
        ),
    ]
