# Generated by Django 4.2.27 on 2026-04-23 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_customuser_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('patient', 'patient'), ('doctor', 'doctor'), ('admin', 'admin')], max_length=10),
        ),
    ]
