version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: docker/prod/Dockerfile
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000 --workers 3
    env_file:
      - .env.prod
    ports:
      - "8000:8000"
    depends_on:
      - redis
    restart: unless-stopped

  celery:
    build:
      context: .
      dockerfile: docker/prod/Dockerfile
    command: python -m celery -A core worker -l info --concurrency 4
    env_file:
      - .env.prod
    depends_on:
      - redis
    restart: unless-stopped

  celery-beat:
    build:
      context: .
      dockerfile: docker/prod/Dockerfile
    command: python -m celery -A core beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    env_file:
      - .env.prod
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    restart: unless-stopped

volumes:
  postgres_data: