# Generated by Django 4.2.27 on 2026-02-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='cancellation_reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
