# Generated by Django 4.2.27 on 2026-02-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_alter_appointment_cancellation_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
