# Generated by Django 4.2.27 on 2026-04-04 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_appointment_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='decline_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('scheduled', 'scheduled'), ('confirmed', 'confirmed'), ('completed', 'completed'), ('cancelled', 'cancelled'), ('declined', 'declined')], default='pending', max_length=20),
        ),
    ]
